/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_comm_Connection */

#ifndef _Included_com_test_comm_Connection
#define _Included_com_test_comm_Connection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_comm_Connection
 * Method:    init_com_port
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_test_comm_Connection_init_1com_1port
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_test_comm_Connection
 * Method:    close_com_port
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_test_comm_Connection_close_1com_1port
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
