/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_protocol_OneTouchUltra */

#ifndef _Included_com_test_protocol_OneTouchUltra
#define _Included_com_test_protocol_OneTouchUltra
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_protocol_OneTouchUltra
 * Method:    ot_ultra_poweron
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_test_protocol_OneTouchUltra_ot_1ultra_1poweron
  (JNIEnv *, jclass);

/*
 * Class:     com_test_protocol_OneTouchUltra
 * Method:    ot_ultra_disconnect
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_test_protocol_OneTouchUltra_ot_1ultra_1disconnect
  (JNIEnv *, jclass);

/*
 * Class:     com_test_protocol_OneTouchUltra
 * Method:    ot_ultra_read_software_info
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_protocol_OneTouchUltra_ot_1ultra_1read_1software_1info
  (JNIEnv *, jclass);

/*
 * Class:     com_test_protocol_OneTouchUltra
 * Method:    ot_ultra_read_serial_number
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_protocol_OneTouchUltra_ot_1ultra_1read_1serial_1number
  (JNIEnv *, jclass);

/*
 * Class:     com_test_protocol_OneTouchUltra
 * Method:    ot_ultra_get_date
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_protocol_OneTouchUltra_ot_1ultra_1get_1date
  (JNIEnv *, jclass);

/*
 * Class:     com_test_protocol_OneTouchUltra
 * Method:    ot_ultra_set_date
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_test_protocol_OneTouchUltra_ot_1ultra_1set_1date
  (JNIEnv *, jclass);

/*
 * Class:     com_test_protocol_OneTouchUltra
 * Method:    ot_ultra_get_unit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_test_protocol_OneTouchUltra_ot_1ultra_1get_1unit
  (JNIEnv *, jclass);

/*
 * Class:     com_test_protocol_OneTouchUltra
 * Method:    ot_ultra_get_nrecords
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_test_protocol_OneTouchUltra_ot_1ultra_1get_1nrecords
  (JNIEnv *, jclass);

/*
 * Class:     com_test_protocol_OneTouchUltra
 * Method:    ot_ultra_read_record_value
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_test_protocol_OneTouchUltra_ot_1ultra_1read_1record_1value
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_test_protocol_OneTouchUltra
 * Method:    ot_ultra_read_record_date
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_protocol_OneTouchUltra_ot_1ultra_1read_1record_1date
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_test_protocol_OneTouchUltra
 * Method:    ot_ultra_delete_all_records
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_test_protocol_OneTouchUltra_ot_1ultra_1delete_1all_1records
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
